DROP SEQUENCE ORGANIZATION_PID_SEQUENCE IF EXISTS;
CREATE SEQUENCE ORGANIZATION_PID_SEQUENCE START WITH 1 INCREMENT BY 1 NOCACHE;

DROP SEQUENCE USER_PID_SEQUENCE IF EXISTS;
CREATE SEQUENCE USER_PID_SEQUENCE START WITH 1 INCREMENT BY 1 NOCACHE;